services:
  - type: web
    name: pos-apotek-risyah-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_NAME
        value: POS_APOTEK
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        value: 10000
      - key: API_PREFIX
        value: /api
      - key: APP_TIMEZONE
        value: Asia/Makassar
      - key: CORS_ORIGIN
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: 6379
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_DB
        value: 0
      - key: REDIS_TTL_SECONDS
        value: 300
      - key: CORS_ALLOW_LOCAL_NETWORK
        value: "false"
      - key: LOCAL_NETWORK_MODE
        value: "false"
      - key: EXPORT_DIR
        value: storage/exports
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: POSTGRES_PRISMA_URL
        sync: false
      - key: POSTGRES_URL
        sync: false
      - key: POSTGRES_URL_NON_POOLING
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_DATABASE
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
    restartPolicyType: on-failure
    restartPolicyMaxRetries: 10
