services:
  postgres:
    image: postgres:16-alpine
    container_name: pos_apotek_risyah_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pos_apotek_risyah
      TZ: Asia/Makassar
    ports:
      - "55432:5432"
    volumes:
      - pos_apotek_risyah_pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d pos_apotek_risyah"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - pos_apotek_network

volumes:
  pos_apotek_risyah_pgdata:

networks:
  pos_apotek_network:
    driver: bridge
